localhost:8080/api/
Accept: application/json

### GET current orders
GET localhost:8080/orders HTTP/1.1
accept: application/json

### GET current orders for kitchen
GET localhost:8080/kitchen/orders HTTP/1.1
accept: application/json

### GET current orders for delivery
GET localhost:8080/delivery/orders HTTP/1.1
accept: application/json

### GET order by id
GET localhost:8080/orders/52099 HTTP/1.1

### PUT update item status
PUT localhost:8080/kitchen/orders/items HTTP/1.1
accept: application/json
Content-Type: application/json

{
  "order_id": 52086,
  "item_id": 0,
  "item_ready": true
}

### PUT update order status from kitchen
PUT localhost:8080/kitchen/orders HTTP/1.1
accept: application/json
Content-Type: application/json

{
  "order_id": 52086,
  "status": true
}

### PUT update order status from delivery
PUT localhost:8080/delivery/orders HTTP/1.1
accept: application/json
Content-Type: application/json

{
  "order_id": 52086,
  "status": true
}

### POST /webhook with customer data
POST localhost:8080/webhook HTTP/1.1
accept: application/json
Content-Type: application/json

{
  "id":4904927297616,
  "admin_graphql_api_id":"gid://shopify/Order/4904927297616",
  "app_id":129785,
  "browser_ip":"181.174.72.236",
  "buyer_accepts_marketing":false,
  "cancel_reason":"None",
  "cancelled_at":"None",
  "cart_token":"None",
  "checkout_id":25572824744016,
  "checkout_token":"7565cb78-f777-4a9a-9a26-1397a6c08041",
  "client_details":{
    "accept_language":"None",
    "browser_height":"None",
    "browser_ip":"181.174.72.236",
    "browser_width":"None",
    "session_hash":"None",
    "user_agent":"Shopify POS/9.1.0/Android/13/samsung/SM-A346M/production"
  },
  "closed_at":"None",
  "confirmation_number":"ZQYFE1C8A",
  "confirmed":true,
  "contact_email":"None",
  "created_at":"2024-02-19T18:32:16-06:00",
  "currency":"GTQ",
  "current_subtotal_price":"505.00",
  "current_subtotal_price_set":{
    "shop_money":{
      "amount":"505.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"505.00",
      "currency_code":"GTQ"
    }
  },
  "current_total_additional_fees_set":"None",
  "current_total_discounts":"0.00",
  "current_total_discounts_set":{
    "shop_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    }
  },
  "current_total_duties_set":"None",
  "current_total_price":"505.00",
  "current_total_price_set":{
    "shop_money":{
      "amount":"505.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"505.00",
      "currency_code":"GTQ"
    }
  },
  "current_total_tax":"54.11",
  "current_total_tax_set":{
    "shop_money":{
      "amount":"54.11",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"54.11",
      "currency_code":"GTQ"
    }
  },
  "customer_locale":"es",
  "device_id":56,
  "discount_codes":[

  ],
  "email":"",
  "estimated_taxes":false,
  "financial_status":"paid",
  "fulfillment_status":"None",
  "landing_site":"None",
  "landing_site_ref":"None",
  "location_id":36285481040,
  "merchant_of_record_app_id":"None",
  "name":"#52099",
  "note":"None",
  "note_attributes":[

  ],
  "number":51099,
  "order_number":52099,
  "order_status_url":"https://boquiteo.com/26830930000/orders/35cc13134938c81325bb8fd947b733b8/authenticate?key=9598d156f1ac31102840f4f7cfb005f3",
  "original_total_additional_fees_set":"None",
  "original_total_duties_set":"None",
  "payment_gateway_names":[
    "Tarjeta de credito"
  ],
  "phone":"None",
  "po_number":"None",
  "presentment_currency":"GTQ",
  "processed_at":"2024-02-19T18:32:14-06:00",
  "reference":"162b7c375090dda4875fabc167a45e37",
  "referring_site":"None",
  "source_identifier":"36285481040-56-1109",
  "source_name":"pos",
  "source_url":"None",
  "subtotal_price":"505.00",
  "subtotal_price_set":{
    "shop_money":{
      "amount":"505.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"505.00",
      "currency_code":"GTQ"
    }
  },
  "tags":"",
  "tax_exempt":false,
  "tax_lines":[
    {
      "price":"54.11",
      "rate":0.12,
      "title":"IVA",
      "price_set":{
        "shop_money":{
          "amount":"54.11",
          "currency_code":"GTQ"
        },
        "presentment_money":{
          "amount":"54.11",
          "currency_code":"GTQ"
        }
      },
      "channel_liable":false
    }
  ],
  "taxes_included":true,
  "test":false,
  "token":"35cc13134938c81325bb8fd947b733b8",
  "total_discounts":"0.00",
  "total_discounts_set":{
    "shop_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    }
  },
  "total_line_items_price":"505.00",
  "total_line_items_price_set":{
    "shop_money":{
      "amount":"505.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"505.00",
      "currency_code":"GTQ"
    }
  },
  "total_outstanding":"0.00",
  "total_price":"505.00",
  "total_price_set":{
    "shop_money":{
      "amount":"505.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"505.00",
      "currency_code":"GTQ"
    }
  },
  "total_shipping_price_set":{
    "shop_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    }
  },
  "total_tax":"54.11",
  "total_tax_set":{
    "shop_money":{
      "amount":"54.11",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"54.11",
      "currency_code":"GTQ"
    }
  },
  "total_tip_received":"0.00",
  "total_weight":0,
  "updated_at":"2024-02-19T18:32:17-06:00",
  "user_id":42319511632,
  "billing_address":"None",
  "customer":{
    "id":5679166357584,
    "email":"None",
    "created_at":"2022-08-08T14:15:07-06:00",
    "updated_at":"2024-02-19T18:32:17-06:00",
    "first_name":"Joselito",
    "last_name":"Ramirez",
    "state":"disabled",
    "note":"None",
    "verified_email":true,
    "multipass_identifier":"None",
    "tax_exempt":false,
    "phone":"None",
    "email_marketing_consent":"None",
    "sms_marketing_consent":"None",
    "tags":"",
    "currency":"GTQ",
    "tax_exemptions":[

    ],
    "admin_graphql_api_id":"gid://shopify/Customer/5679166357584",
    "default_address":{
      "id":6908305342544,
      "customer_id":5679166357584,
      "first_name":"Joselito",
      "last_name":" Ramirez",
      "company":"None",
      "address1":"Condominio los encinos",
      "address2":"Casa 22 santuaria muxbal",
      "city":"Guatemala",
      "province":"Guatemala",
      "country":"Guatemala",
      "zip":"76960722",
      "phone":"",
      "name":"Joselito  Ramirez",
      "province_code":"GUA",
      "country_code":"GT",
      "country_name":"Guatemala",
      "default":true
    }
  },
  "discount_applications":[

  ],
  "fulfillments":[

  ],
  "line_items":[
    {
      "id":12078990688336,
      "admin_graphql_api_id":"gid://shopify/LineItem/12078990688336",
      "attributed_staffs":[

      ],
      "current_quantity":2,
      "fulfillable_quantity":2,
      "fulfillment_service":"manual",
      "fulfillment_status":"None",
      "gift_card":false,
      "grams":0,
      "name":"Robalo Incrustado con Almendras",
      "price":"180.00",
      "price_set":{
        "shop_money":{
          "amount":"180.00",
          "currency_code":"GTQ"
        },
        "presentment_money":{
          "amount":"180.00",
          "currency_code":"GTQ"
        }
      },
      "product_exists":true,
      "product_id":6792159395920,
      "properties":[

      ],
      "quantity":2,
      "requires_shipping":true,
      "sku":"",
      "taxable":true,
      "title":"Robalo Incrustado con Almendras",
      "total_discount":"0.00",
      "total_discount_set":{
        "shop_money":{
          "amount":"0.00",
          "currency_code":"GTQ"
        },
        "presentment_money":{
          "amount":"0.00",
          "currency_code":"GTQ"
        }
      },
      "variant_id":40034261762128,
      "variant_inventory_management":"None",
      "variant_title":"None",
      "vendor":"La Pista",
      "tax_lines":[
        {
          "channel_liable":false,
          "price":"38.58",
          "price_set":{
            "shop_money":{
              "amount":"38.58",
              "currency_code":"GTQ"
            },
            "presentment_money":{
              "amount":"38.58",
              "currency_code":"GTQ"
            }
          },
          "rate":0.12,
          "title":"IVA"
        }
      ],
      "duties":[

      ],
      "discount_allocations":[

      ]
    },
    {
      "id":12078990721104,
      "admin_graphql_api_id":"gid://shopify/LineItem/12078990721104",
      "attributed_staffs":[

      ],
      "current_quantity":1,
      "fulfillable_quantity":1,
      "fulfillment_service":"manual",
      "fulfillment_status":"None",
      "gift_card":false,
      "grams":0,
      "name":"Bocata de Pollo a la Plancha - Papas Fritas",
      "price":"125.00",
      "price_set":{
        "shop_money":{
          "amount":"125.00",
          "currency_code":"GTQ"
        },
        "presentment_money":{
          "amount":"125.00",
          "currency_code":"GTQ"
        }
      },
      "product_exists":true,
      "product_id":6812510224464,
      "properties":[

      ],
      "quantity":1,
      "requires_shipping":true,
      "sku":"",
      "taxable":true,
      "title":"Bocata de Pollo a la Plancha",
      "total_discount":"0.00",
      "total_discount_set":{
        "shop_money":{
          "amount":"0.00",
          "currency_code":"GTQ"
        },
        "presentment_money":{
          "amount":"0.00",
          "currency_code":"GTQ"
        }
      },
      "variant_id":40172395167824,
      "variant_inventory_management":"None",
      "variant_title":"Papas Fritas",
      "vendor":"La Pista",
      "tax_lines":[
        {
          "channel_liable":false,
          "price":"13.39",
          "price_set":{
            "shop_money":{
              "amount":"13.39",
              "currency_code":"GTQ"
            },
            "presentment_money":{
              "amount":"13.39",
              "currency_code":"GTQ"
            }
          },
          "rate":0.12,
          "title":"IVA"
        }
      ],
      "duties":[

      ],
      "discount_allocations":[

      ]
    },
    {
      "id":12078990753872,
      "admin_graphql_api_id":"gid://shopify/LineItem/12078990753872",
      "attributed_staffs":[

      ],
      "current_quantity":1,
      "fulfillable_quantity":1,
      "fulfillment_service":"manual",
      "fulfillment_status":"None",
      "gift_card":false,
      "grams":0,
      "name":"Cerveza Gallo",
      "price":"20.00",
      "price_set":{
        "shop_money":{
          "amount":"20.00",
          "currency_code":"GTQ"
        },
        "presentment_money":{
          "amount":"20.00",
          "currency_code":"GTQ"
        }
      },
      "product_exists":true,
      "product_id":4599247241296,
      "properties":[

      ],
      "quantity":1,
      "requires_shipping":true,
      "sku":"",
      "taxable":true,
      "title":"Cerveza Gallo",
      "total_discount":"0.00",
      "total_discount_set":{
        "shop_money":{
          "amount":"0.00",
          "currency_code":"GTQ"
        },
        "presentment_money":{
          "amount":"0.00",
          "currency_code":"GTQ"
        }
      },
      "variant_id":32322307948624,
      "variant_inventory_management":"None",
      "variant_title":"None",
      "vendor":"Boquiteo",
      "tax_lines":[
        {
          "channel_liable":false,
          "price":"2.14",
          "price_set":{
            "shop_money":{
              "amount":"2.14",
              "currency_code":"GTQ"
            },
            "presentment_money":{
              "amount":"2.14",
              "currency_code":"GTQ"
            }
          },
          "rate":0.12,
          "title":"IVA"
        }
      ],
      "duties":[

      ],
      "discount_allocations":[

      ]
    }
  ],
  "payment_terms":"None",
  "refunds":[

  ],
  "shipping_address":"None",
  "shipping_lines":[

  ]
}

### POST /webhook with UberEats data
POST localhost:8080/webhook HTTP/1.1
accept: application/json
Content-Type: application/json

{
  "id":4904060616784,
  "admin_graphql_api_id":"gid://shopify/Order/4904060616784",
  "app_id":129785,
  "browser_ip":"181.209.144.124",
  "buyer_accepts_marketing":false,
  "cancel_reason":"None",
  "cancelled_at":"None",
  "cart_token":"None",
  "checkout_id":25569366966352,
  "checkout_token":"e28e7308-e0d8-4167-8c6b-3be2190090bf",
  "client_details":{
    "accept_language":"None",
    "browser_height":"None",
    "browser_ip":"181.209.144.124",
    "browser_width":"None",
    "session_hash":"None",
    "user_agent":"Shopify POS/9.1.0/Android/10/HUAWEI/ELE-L29/production"
  },
  "closed_at":"None",
  "confirmation_number":"UDNWP4LNT",
  "confirmed":true,
  "contact_email":"None",
  "created_at":"2024-02-18T20:02:05-06:00",
  "currency":"GTQ",
  "current_subtotal_price":"121.00",
  "current_subtotal_price_set":{
    "shop_money":{
      "amount":"121.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"121.00",
      "currency_code":"GTQ"
    }
  },
  "current_total_additional_fees_set":"None",
  "current_total_discounts":"0.00",
  "current_total_discounts_set":{
    "shop_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    }
  },
  "current_total_duties_set":"None",
  "current_total_price":"121.00",
  "current_total_price_set":{
    "shop_money":{
      "amount":"121.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"121.00",
      "currency_code":"GTQ"
    }
  },
  "current_total_tax":"12.96",
  "current_total_tax_set":{
    "shop_money":{
      "amount":"12.96",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"12.96",
      "currency_code":"GTQ"
    }
  },
  "customer_locale":"es",
  "device_id":45,
  "discount_codes":[

  ],
  "email":"",
  "estimated_taxes":false,
  "financial_status":"paid",
  "fulfillment_status":"None",
  "landing_site":"None",
  "landing_site_ref":"None",
  "location_id":36285481040,
  "merchant_of_record_app_id":"None",
  "name":"#52086",
  "note":"None",
  "note_attributes":[

  ],
  "number":51086,
  "order_number":52086,
  "order_status_url":"https://boquiteo.com/26830930000/orders/1ce9becfdc3ed9a26717d438488088bd/authenticate?key=a07de2ecd8707679625b60a90f74f1e3",
  "original_total_additional_fees_set":"None",
  "original_total_duties_set":"None",
  "payment_gateway_names":[
    "Uber eats "
  ],
  "phone":"None",
  "po_number":"None",
  "presentment_currency":"GTQ",
  "processed_at":"2024-02-18T20:02:04-06:00",
  "reference":"3cf71e3fbefe8c4864bce12bcfbc53ab",
  "referring_site":"None",
  "source_identifier":"36285481040-45-5610",
  "source_name":"pos",
  "source_url":"None",
  "subtotal_price":"121.00",
  "subtotal_price_set":{
    "shop_money":{
      "amount":"121.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"121.00",
      "currency_code":"GTQ"
    }
  },
  "tags":"",
  "tax_exempt":false,
  "tax_lines":[
    {
      "price":"12.96",
      "rate":0.12,
      "title":"IVA",
      "price_set":{
        "shop_money":{
          "amount":"12.96",
          "currency_code":"GTQ"
        },
        "presentment_money":{
          "amount":"12.96",
          "currency_code":"GTQ"
        }
      },
      "channel_liable":false
    }
  ],
  "taxes_included":true,
  "test":false,
  "token":"1ce9becfdc3ed9a26717d438488088bd",
  "total_discounts":"0.00",
  "total_discounts_set":{
    "shop_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    }
  },
  "total_line_items_price":"121.00",
  "total_line_items_price_set":{
    "shop_money":{
      "amount":"121.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"121.00",
      "currency_code":"GTQ"
    }
  },
  "total_outstanding":"0.00",
  "total_price":"121.00",
  "total_price_set":{
    "shop_money":{
      "amount":"121.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"121.00",
      "currency_code":"GTQ"
    }
  },
  "total_shipping_price_set":{
    "shop_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"0.00",
      "currency_code":"GTQ"
    }
  },
  "total_tax":"12.96",
  "total_tax_set":{
    "shop_money":{
      "amount":"12.96",
      "currency_code":"GTQ"
    },
    "presentment_money":{
      "amount":"12.96",
      "currency_code":"GTQ"
    }
  },
  "total_tip_received":"0.00",
  "total_weight":0,
  "updated_at":"2024-02-18T20:02:06-06:00",
  "user_id":42319511632,
  "billing_address":"None",
  "customer":{
    "id":3714155905104,
    "email":"None",
    "created_at":"2020-12-20T12:52:05-06:00",
    "updated_at":"2024-02-18T20:02:08-06:00",
    "first_name":"UBER",
    "last_name":"EATS",
    "state":"disabled",
    "note":"",
    "verified_email":true,
    "multipass_identifier":"None",
    "tax_exempt":false,
    "phone":"None",
    "email_marketing_consent":"None",
    "sms_marketing_consent":"None",
    "tags":"Uber",
    "currency":"GTQ",
    "tax_exemptions":[

    ],
    "admin_graphql_api_id":"gid://shopify/Customer/3714155905104",
    "default_address":{
      "id":6333990305872,
      "customer_id":3714155905104,
      "first_name":"UBER ",
      "last_name":"EATS",
      "company":"CF",
      "address1":"Ciudad",
      "address2":"Ciudad ",
      "city":"Guatemala",
      "province":"Guatemala",
      "country":"Guatemala",
      "zip":"Cf",
      "phone":"None",
      "name":"UBER  EATS",
      "province_code":"GUA",
      "country_code":"GT",
      "country_name":"Guatemala",
      "default":true
    }
  },
  "discount_applications":[

  ],
  "fulfillments":[

  ],
  "line_items":[
    {
      "id":12077269614672,
      "admin_graphql_api_id":"gid://shopify/LineItem/12077269614672",
      "attributed_staffs":[

      ],
      "current_quantity":1,
      "fulfillable_quantity":1,
      "fulfillment_service":"manual",
      "fulfillment_status":"None",
      "gift_card":false,
      "grams":0,
      "name":"APP Cheesest Christ Burger - La Famosa Burger de Luka - Papas Fritas / Normal",
      "price":"121.00",
      "price_set":{
        "shop_money":{
          "amount":"121.00",
          "currency_code":"GTQ"
        },
        "presentment_money":{
          "amount":"121.00",
          "currency_code":"GTQ"
        }
      },
      "product_exists":true,
      "product_id":6568265515088,
      "properties":[

      ],
      "quantity":1,
      "requires_shipping":true,
      "sku":"",
      "taxable":true,
      "title":"APP Cheesest Christ Burger - La Famosa Burger de Luka",
      "total_discount":"0.00",
      "total_discount_set":{
        "shop_money":{
          "amount":"0.00",
          "currency_code":"GTQ"
        },
        "presentment_money":{
          "amount":"0.00",
          "currency_code":"GTQ"
        }
      },
      "variant_id":39406970175568,
      "variant_inventory_management":"None",
      "variant_title":"Papas Fritas / Normal",
      "vendor":"Luka",
      "tax_lines":[
        {
          "channel_liable":false,
          "price":"12.96",
          "price_set":{
            "shop_money":{
              "amount":"12.96",
              "currency_code":"GTQ"
            },
            "presentment_money":{
              "amount":"12.96",
              "currency_code":"GTQ"
            }
          },
          "rate":0.12,
          "title":"IVA"
        }
      ],
      "duties":[

      ],
      "discount_allocations":[

      ]
    }
  ],
  "payment_terms":"None",
  "refunds":[

  ],
  "shipping_address":"None",
  "shipping_lines":[

  ]
}

